services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: barberservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql


  # springapp:
    # build: .
    # depends_on:
      # - postgresqldb
    # ports:
      # - '8081:8080'